# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archway < Formula
  desc "Architecture-aware service composer and enforcer"
  homepage "https://github.com/dcsg/archway"
  version "0.2.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dcsg/archway/releases/download/v0.2.0/archway_0.2.0_darwin_amd64.tar.gz"
      sha256 "2bfc06cd80ab368b45404ee1d0d51bc7c0da3124db2913cd21c1090378419dc7"

      define_method(:install) do
        bin.install "archway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dcsg/archway/releases/download/v0.2.0/archway_0.2.0_darwin_arm64.tar.gz"
      sha256 "67d3e30f755adf8101ac999228b7776a64fe286c9481c3dfa685793e6ebf2fb7"

      define_method(:install) do
        bin.install "archway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcsg/archway/releases/download/v0.2.0/archway_0.2.0_linux_amd64.tar.gz"
      sha256 "2e2795e475d74a5b1d0a871a1a57bcd610a41cd353a0e3cd69e3a9dfb611c89d"
      define_method(:install) do
        bin.install "archway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcsg/archway/releases/download/v0.2.0/archway_0.2.0_linux_arm64.tar.gz"
      sha256 "d39b523a7a85f2832fdd3bba5c554f06243d6da1a58d284ba15f0c732079ab3f"
      define_method(:install) do
        bin.install "archway"
      end
    end
  end

  def post_install
    system "#{bin}/archway", "setup"
  end

  test do
    system "#{bin}/archway", "version"
  end
end
