# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archway < Formula
  desc "Architecture-aware service composer and enforcer"
  homepage "https://github.com/dcsg/archway"
  version "0.1.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_darwin_amd64.tar.gz"
      sha256 "02e5de450b7f8d16b180b1724ed25832f99b0a3c160b0e83f49c5ffe84db81a9"

      define_method(:install) do
        bin.install "archway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_darwin_arm64.tar.gz"
      sha256 "15868a6ef6d222633ac9976604a245d4ef6bc41308f91383db0f4c9c7eb03c3f"

      define_method(:install) do
        bin.install "archway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_linux_amd64.tar.gz"
      sha256 "51d39ff2897b1018dee9912cb2c4119d43ce525d74339a7ba4d6fd254d825526"
      define_method(:install) do
        bin.install "archway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_linux_arm64.tar.gz"
      sha256 "83543a278daf42c2b97a74e28360bcb6b5dd75f76e73a00caf1814f974749463"
      define_method(:install) do
        bin.install "archway"
      end
    end
  end

  test do
    system "#{bin}/archway", "version"
  end
end
