# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archway < Formula
  desc "Architecture-aware service composer and enforcer"
  homepage "https://github.com/dcsg/archway"
  version "0.1.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_darwin_amd64.tar.gz"
      sha256 "a74cc1c46adb3703cd58815d005daf8d5f849651323fd10c59380fc892c23616"

      define_method(:install) do
        bin.install "archway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_darwin_arm64.tar.gz"
      sha256 "a90e87edc4857a843237dcb4bde2eb2e233f64a36f50a95a656c1b59819ce4aa"

      define_method(:install) do
        bin.install "archway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_linux_amd64.tar.gz"
      sha256 "64357e3a7297fb37ea5fcab04b7ef4add335bdbf30b462e455af32205861e8d3"
      define_method(:install) do
        bin.install "archway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcsg/archway/releases/download/v0.1.0/archway_0.1.0_linux_arm64.tar.gz"
      sha256 "cbb160a4d78d30c6afe711b79cb2a6fb72294b9aaedef78e1d5a83ff237271b1"
      define_method(:install) do
        bin.install "archway"
      end
    end
  end

  test do
    system "#{bin}/archway", "version"
  end
end
